### ISSUE TITLE
Library no longer works with Python 3.10

### ISSUE THREAD

**Issue by Beenhakker** [brennv/namedtupled#25]
Library no longer imports correctly in Python 3.10:

```
from collections import Mapping, namedtuple, UserDict
ImportError: cannot import name 'Mapping' from 'collections
```

`Mapping` is moved to `collections.abc`
